# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPANPLUS-Dist-Build
version:      0.02
version_from: lib/CPANPLUS/Dist/Build.pm
installdirs:  site
requires:
    CPANPLUS:                      0.055
    File::Spec:                    0
    IPC::Cmd:                      0.23
    Locale::Maketext::Simple:      0
    Module::Build:                 0.2611
    Module::Load::Conditional:     0.06
    Module::Pluggable:             2.4
    Params::Check:                 0.22
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
